name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        target: [ x86_64-pc-windows-msvc, i686-pc-windows-msvc, aarch64-pc-windows-msvc, i686-pc-windows-gnu ]
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Set up MinGW
        if: ${{ matrix.target == 'i686-pc-windows-gnu' }}
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x86
      - run: rustup target add ${{ matrix.target }}
      - run: cargo build --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/fabric-installer-native-bootstrap.exe
